// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cytefvugfpdasdkwdpul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dGVmdnVnZnBkYXNka3dkcHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzIyOTcsImV4cCI6MjA3MTYwODI5N30.uVIvS1GRPyOgYgq42EP3b2Mnj2uvjHm_Z1lRcStFNdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});